
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version ="1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/sha1n/go-playground"
